DROP DATABASE IF EXISTS modelamiento;
CREATE DATABASE IF NOT EXISTS modelamiento;
USE modelamiento;

CREATE TABLE IF NOT EXISTS personas(
id INT NOT NULL AUTO_INCREMENT,
nombre VARCHAR(45) NOT NULL,
apellido VARCHAR(45) NOT NULL,
tipoDocumento  VARCHAR(45) NOT NULL,
documento INT NOT NULL,
telefono VARCHAR(45)  NOT NULL,
correo VARCHAR(45)  NOT NULL,
password VARCHAR(45)  NOT NULL,
direccion VARCHAR(45)  NOT NULL,
PRIMARY KEY(id)
)ENGINE InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS clientes(
id INT NOT NULL AUTO_INCREMENT,
idPersona INT NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY (idPersona) REFERENCES personas(id)
)ENGINE InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS fichaTecnicas(
placa VARCHAR(45) NOT NULL,
tipoVehiculo VARCHAR(45) NOT NULL,
modelo INT NOT NULL,
marca VARCHAR(45) NOT NULL,
cantPuestos INT NOT NULL,
ultimoMantinimiento DATETIME NOT NULL,
documentos VARCHAR(45) NOT NULL,

PRIMARY KEY(placa)
)ENGINE InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS vehiculos(
id INT NOT NULL AUTO_INCREMENT,
idFichaTecnica VARCHAR(45) NOT NULL,

PRIMARY KEY(id),
FOREIGN KEY (idFichaTecnica) REFERENCES fichaTecnicas(placa)
)ENGINE InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE IF NOT EXISTS trasportadores(
id INT NOT NULL AUTO_INCREMENT,
idPersona INT NOT NULL,
idVehiculo INT NOT NULL,
experiencia INT NOT NULL,
cv VARCHAR(45) NULL,
edad INT NULL,
PRIMARY KEY(id),
FOREIGN KEY (idPersona) REFERENCES personas(id),
FOREIGN KEY (idVehiculo) REFERENCES vehiculos(id)
)ENGINE InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS rutas(
id INT NOT NULL AUTO_INCREMENT,
ciudadOrigen VARCHAR(45) NOT NULL,
ciudadDestino VARCHAR(45) NOT NULL,
distancia DOUBLE NOT NULL,
horaSalida TIME NOT NULL,
tiempoAproximado TIME NOT NULL,
PRIMARY KEY(id)
)ENGINE InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS viajes(
id INT NOT NULL AUTO_INCREMENT,
idTransportador INT NOT NULL,
idRuta INT NOT NULL,
valor DOUBLE NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY (idTransportador) REFERENCES trasportadores(id),
FOREIGN KEY (idRuta) REFERENCES rutas(id)
)ENGINE InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pasajeros(
id INT NOT NULL AUTO_INCREMENT,
idCliente INT NOT NULL,
idViaje INT NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY (idCliente) REFERENCES clientes(id),
FOREIGN KEY (idViaje) REFERENCES viajes(id)
)ENGINE InnoDB DEFAULT CHARSET=utf8mb4;

