CREATE DATABASE IF NOT EXISTS modelamiento;
USE modelamiento;

CREATE TABLE IF NOT EXISTS tipoDocumento(
id INT NOT NULL AUTO_INCREMENT,
nombre VARCHAR(45) NOT NULL,
PRIMARY KEY(id)
)ENGINE InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS persona(
id INT NOT NULL AUTO_INCREMENT,
nombre VARCHAR(45) NOT NULL,
apellido VARCHAR(45) NOT NULL,
idTipoDocumento INT NOT NULL,
telefono VARCHAR(45)  NOT NULL,
correo VARCHAR(45)  NOT NULL,
password VARCHAR(45)  NOT NULL,
direccion VARCHAR(45)  NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY (idTipoDocumento) REFERENCES tipoDocumento(id)
)ENGINE InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cliente(
id INT NOT NULL AUTO_INCREMENT,
idPersona INT NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY (idPersona) REFERENCES persona(id)
)ENGINE InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS vehiculo(
id INT NOT NULL AUTO_INCREMENT,
idFichaTenica INT NOT NULL,

PRIMARY KEY(id),
FOREIGN KEY (idFichaTenica) REFERENCES fichaTecnica(placa)
)ENGINE InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS fichaTecnica(
placa VARCHAR(45) NOT NULL,
tipoVehiculo VARCHAR(45) NOT NULL,
modelo INT NOT NULL,
marca VARCHAR(45) NOT NULL,
cantPuestos INT NOT NULL,
ultimoMantinimiento DATETIME NOT NULL,
documentos VARCHAR(45) NOT NULL,

PRIMARY KEY(placa)
)ENGINE InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS trasportadores(
id INT NOT NULL AUTO_INCREMENT,
idPersona INT NOT NULL,
idVehiculo INT NOT NULL,
ruta VARCHAR(100) NULL,
experiencia INT NOT NULL,
cv VARCHAR(45) NULL,
edad INT NULL,
PRIMARY KEY(id),
FOREIGN KEY (idPersona) REFERENCES persona(id),
FOREIGN KEY (idVehiculo) REFERENCES vehiculo(id)
)ENGINE InnoDB DEFAULT CHARSET=utf8mb4;


